appname: tx_base_api
db: 
  encoding: utf8mb4
  socket: /tmp/mysql.sock
  database: txhims_staging
  pool: 25
  username: root
  password: n[h^nM06
  host: test.tongxinyiliao.com
  port: 3306
redis: 
  protocol: tcp
  host: test.tongxinyiliao.com
  port: 6379
  password: b1e41f0f3dc551703dc51c64d1970fe5
rabbit:
  url: amqp://rabbitmq:123456@localhost:5672/