appname: tx_base_api

db: 
  encoding: utf8mb4
  pool: 5
  username: root
  password: root
  host: localhost
  port: 3306
  socket: /tmp/mysql.sock
  database: txhims

redis: 
  protocol: tcp
  host: localhost
  port: 6379
  password: ''

rabbit:
  url: amqp://rabbitmq:123456@localhost:5672/