appname: tx_base_api
db: 
  encoding: utf8mb4
  socket: /tmp/mysql.sock
  database: txhims_production
  pool: 25
  username: pro_txdb
  password: 'Tongxin2014'
  host: rdsarjziaiq3e2a.mysql.rds.aliyuncs.com
  port: 3306
redis: 
  protocol: tcp
  host: 01afeb587c3146dd.m.cnbja.kvstore.aliyuncs.com
  port: 6379
  password: 01afeb587c3146dd:TongXin2015
rabbit:
  url: amqp://rabbitmq:123456@localhost:5672/